-- MySQL Script generated by MySQL Workbench
-- Mon Sep 22 20:47:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bem-estar-animal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bem-estar-animal` ;

-- -----------------------------------------------------
-- Schema bem-estar-animal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bem-estar-animal` DEFAULT CHARACTER SET utf8 ;
USE `bem-estar-animal` ;

-- -----------------------------------------------------
-- Table `bem-estar-animal`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`funcionario` (
  `funcionario_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `registro` VARCHAR(45) NULL,
  `funcao` VARCHAR(45) NULL,
  PRIMARY KEY (`funcionario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bem-estar-animal`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`endereco` (
  `endereco_id` INT NOT NULL,
  `logradouro` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `ponto_de_referencia` VARCHAR(45) NULL,
  PRIMARY KEY (`endereco_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bem-estar-animal`.`denunciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`denunciante` (
  `denunciante_id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`denunciante_id`, `endereco_id`),
  INDEX `fk_denunciante_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_denunciante_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `bem-estar-animal`.`endereco` (`endereco_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bem-estar-animal`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`ficha` (
  `ficha_id` INT NOT NULL,
  `processo` VARCHAR(45) NULL,
  `recebido_por` VARCHAR(45) NULL,
  `data` TIMESTAMP(6) NULL,
  `hora` TIMESTAMP(6) NULL,
  `assunto` VARCHAR(45) NULL,
  `desfecho_da_notificacao` VARCHAR(45) NULL,
  `data_tramite` TIMESTAMP(6) NULL,
  `hora_tramite` TIMESTAMP(6) NULL,
  `historico` VARCHAR(45) NULL,
  `animal` VARCHAR(45) NULL,
  `funcionario_id` INT NOT NULL,
  `denunciante_id` INT NOT NULL,
  PRIMARY KEY (`ficha_id`, `funcionario_id`, `denunciante_id`),
  INDEX `fk_ficha_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  INDEX `fk_ficha_denunciante1_idx` (`denunciante_id` ASC) VISIBLE,
  CONSTRAINT `fk_ficha_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `bem-estar-animal`.`funcionario` (`funcionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_denunciante1`
    FOREIGN KEY (`denunciante_id`)
    REFERENCES `bem-estar-animal`.`denunciante` (`denunciante_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bem-estar-animal`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`login` (
  `login_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `funcionario_id` INT NOT NULL,
  PRIMARY KEY (`login_id`, `funcionario_id`),
  INDEX `fk_login_funcionario1_idx` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_login_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `bem-estar-animal`.`funcionario` (`funcionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bem-estar-animal`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem-estar-animal`.`role` (
  `role_id` INT NOT NULL,
  `login_id` INT NOT NULL,
  PRIMARY KEY (`role_id`, `login_id`),
  INDEX `fk_role_login1_idx` (`login_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_login1`
    FOREIGN KEY (`login_id`)
    REFERENCES `bem-estar-animal`.`login` (`funcionario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
