-- MySQL Script generated by MySQL Workbench
-- sex 17 out 2025 11:04:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bem_estar_animal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bem_estar_animal` ;

-- -----------------------------------------------------
-- Schema bem_estar_animal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bem_estar_animal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bem_estar_animal` ;

-- -----------------------------------------------------
-- Table `bem_estar_animal`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem_estar_animal`.`endereco` (
  `id_endereco` BIGINT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `ponto_de_referencia` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bem_estar_animal`.`denunciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem_estar_animal`.`denunciante` (
  `id_denunciante` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  `endereco_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_denunciante`),
  INDEX `endereco_id` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `denunciante_ibfk_1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `bem_estar_animal`.`endereco` (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bem_estar_animal`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem_estar_animal`.`funcionario` (
  `id_funcionario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `registro` VARCHAR(255) NULL DEFAULT NULL,
  `funcao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bem_estar_animal`.`ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bem_estar_animal`.`ficha` (
  `id_ficha` BIGINT NOT NULL AUTO_INCREMENT,
  `processo_ouvidoria` VARCHAR(50) NULL DEFAULT NULL,
  `recebido_por_secretaria` VARCHAR(40) NULL DEFAULT NULL,
  `recebido_por_ouvidoria` VARCHAR(40) NULL,
  `data_ouvidoria` DATETIME NULL DEFAULT NULL,
  `hora_ouvidoria` DATETIME NULL DEFAULT NULL,
  `denunciante_id` BIGINT NULL DEFAULT NULL,
  `recebido_por_ouvidoria` VARCHAR(40) NULL DEFAULT NULL,
  `desfecho_da_notificacao` VARCHAR(500) NULL DEFAULT NULL,
  `data_secretaria` DATETIME NULL DEFAULT NULL,
  `hora_secretaria` DATETIME NULL DEFAULT NULL,
  `funcionario_id` BIGINT NULL DEFAULT NULL,
  `historico` VARCHAR(255) NULL DEFAULT NULL,
  `animal` VARCHAR(10) NULL DEFAULT NULL,
  `processo_secretaria` VARCHAR(50) NULL,
  `fiscal` VARCHAR(50) NULL,
  `data_tramite` DATETIME NULL,
  `hora_tramite` DATETIME NULL,
  PRIMARY KEY (`id_ficha`),
  INDEX `denunciante_id` (`denunciante_id` ASC) VISIBLE,
  INDEX `funcionario_id` (`funcionario_id` ASC) VISIBLE,
  CONSTRAINT `ficha_ibfk_1`
    FOREIGN KEY (`denunciante_id`)
    REFERENCES `bem_estar_animal`.`denunciante` (`id_denunciante`),
  CONSTRAINT `ficha_ibfk_2`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `bem_estar_animal`.`funcionario` (`id_funcionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
